#!/usr/bin/env bash

info () {
  printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] %s\n" "$1"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
  echo ''
  exit
}

brew_cask_install_by_app () {
  export APP_NAME=$1
  export APP_CLI=$2
  if test ! -e "/Applications/$APP_NAME.app"
  then
      info "Installing $APP_CLI"
      brew cask install $APP_CLI
  else
      success "skipped installing $APP_NAME"
  fi
}

brew_cask_install_by_cli () {
  export APP_CLI=$1
  export APP_NAME=$2
  if test ! $(which $APP_CLI)
  then
      info "Installing $APP_NAME"
      brew cask install $APP_NAME
  else
      success "skipped installing $APP_NAME"
  fi
}