#!/usr/bin/env bash

info () {
  printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] %s\n" "$1"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
  echo ''
  exit
}

brew_cask_install () {
  export APP_NAME=$1
  if test ! -e "/Applications/$APP_NAME.app"
  then
      info "Installing $APP_NAME"
      brew cask install $APP_NAME
  else
      success "skipped installing $APP_NAME"
  fi
}